config/routes.rb
Cute::Application.routes.draw do
  resources :baby_animals

  

end

app/models/baby_animal.rb
class BabyAnimal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baby_animals_controller.rb
class BabyAnimalsController < ApplicationController
  before_action :set_baby_animal, only: [:show, :edit, :update, :destroy]

  # GET /baby_animals
  # GET /baby_animals.json
  def index
    @baby_animals = BabyAnimal.all
  end

  # GET /baby_animals/1
  # GET /baby_animals/1.json
  def show
  end

  # GET /baby_animals/new
  def new
    @baby_animal = BabyAnimal.new
  end

  # GET /baby_animals/1/edit
  def edit
  end

  # POST /baby_animals
  # POST /baby_animals.json
  def create
    @baby_animal = BabyAnimal.new(baby_animal_params)

    respond_to do |format|
      if @baby_animal.save
        format.html { redirect_to @baby_animal, notice: 'Baby animal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @baby_animal }
      else
        format.html { render action: 'new' }
        format.json { render json: @baby_animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baby_animals/1
  # PATCH/PUT /baby_animals/1.json
  def update
    respond_to do |format|
      if @baby_animal.update(baby_animal_params)
        format.html { redirect_to @baby_animal, notice: 'Baby animal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @baby_animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baby_animals/1
  # DELETE /baby_animals/1.json
  def destroy
    @baby_animal.destroy
    respond_to do |format|
      format.html { redirect_to baby_animals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby_animal
      @baby_animal = BabyAnimal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_animal_params
      params.require(:baby_animal).permit(:title, :img_url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baby_animals_helper.rb
module BabyAnimalsHelper
end

app/views/baby_animals/_form.html.erb
<%= form_for(@baby_animal) do |f| %>
  <% if @baby_animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baby_animal.errors.count, "error") %> prohibited this baby_animal from being saved:</h2>

      <ul>
      <% @baby_animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "text", :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url, :class => "text", :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "text", :class => "form-control" %>
  </div>
  <p></p>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/baby_animals/edit.html.erb
<h1>Edit This Baby Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @baby_animal %> |
<%= link_to 'Back', baby_animals_path %>

app/views/baby_animals/index.html.erb
<div class="container">
<div class="jumbotron">
  <h1>Baby Animals!</h1>
  <p>Adorable, fluffy, and <b>super</b> cute. Everything to lighten your day!</p>
  <p><a href="<%= new_baby_animal_path %>" class="btn btn-primary btn-lg" role="button">Upload</a></p>
  </div>
</div>

<% @baby_animals.each do |baby_animal| %>

<div class="container">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
    <%= baby_animal.title %>
    </h3>
  </div>
  <div class="panel-body">
    <img src="<%= baby_animal.img_url %>">
  </div>
  <div class="panel-footer">
        <td><%= link_to 'Show', baby_animal %></td> |
        <td><%= link_to 'Edit', edit_baby_animal_path(baby_animal) %></td> |
        <td><%= link_to 'Destroy', baby_animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
</div>
</div>

<% end %>

app/views/baby_animals/new.html.erb
<h1>New Baby Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', baby_animals_path %>

app/views/baby_animals/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
<%= @baby_animal.title %>
</h2>
<p>
  <img src="<%= @baby_animal.img_url %>">
</p>


<p>
  <strong>Title:</strong>
  <%= @baby_animal.title %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @baby_animal.img_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @baby_animal.description %>
</p>

<%= link_to 'Edit', edit_baby_animal_path(@baby_animal) %> |
<%= link_to 'Back', baby_animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

<html>
<head>
  <title>Cute</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>